export const prompts = [
    "What was the last movie you watched, and what did you think of it?",
    "If you could time travel, which historical period would you go to?",
    "What is your favorite childhood food?",
    "Do you have any special talents that few people know about?",
    "What is your favorite season of the year, and why?",
    "If you could instantly learn any skill, what would you choose?",
    "Have you ever had an unusual encounter with a wild animal?",
    "What is your favorite book, and why would you recommend it?",
    "What is your favorite leisure activity to relax?",
    "If you won the lottery, what would be the first thing you would do?",
    "Have you ever participated in a TV or radio program?",
    "What is the most beautiful place you have ever visited?",
    "Who are your favorite music or artists?",
    "Do you have any life goals that you haven't achieved yet?",
    "If you could choose a superpower, what would it be?",
    "Have you ever done any volunteer work? How was it?",
    "What is the funniest thing that has ever happened to you at work?",
    "Do you have any hobbies you'd love to share?",
    "If you could spend a day with a celebrity, who would you choose?",
    "What is your funniest childhood memory?",
    "If you were an animal, what do you think you would be, and why?",
    "What is your current favorite TV series?",
    "Have you had any unforgettable trips? Tell us about them.",
    "If you could meet any historical figure, who would it be?",
    "What is the strangest thing you have ever eaten?",
    "What is your favorite sport or physical activity?",
    "If you could invent a holiday, what would it be and why?",
    "What is your favorite joke?",
    "Have you ever participated in a charity event?",
    "What is your favorite international dish?",
    "If you could instantly learn a new language, which one would it be?",
    "What is your favorite place in the city where you live?",
    "Have you ever had an encounter with a celebrity? How was it?",
    "What is the best travel advice you have received?",
    "Do you have any personal projects or creative hobbies?",
    "What is your favorite board game or video game?",
    "If you could travel anywhere in the world right now, where would you go?",
    "What is your favorite TV or streaming station for series?",
    "What is the bravest thing you have ever done in life?",
    "Do you have any musical talent?",
    "What is your favorite dessert?",
    "What is the last book you read, and what did you think of it?",
    "Have you ever tried any extreme sports?",
    "What is your favorite place to relax after work?",
    "If you could live in any historical era, when would it be?",
    "What is your favorite museum?",
    "If you were a cartoon character, who would you be?",
    "Have you ever won any awards or recognition for something?",
    "What is your favorite beverage?",
    "Have you had any funny experiences while traveling?",
    "What is your favorite comedy movie?",
    "If you could learn a new sports skill instantly, what would you choose?",
    "Do you have any pets? What are their names?",
    "What is the most exotic place you have visited?",
    "If you could invent something, what would it be?",
    "What is your favorite cultural festival or event?",
    "What is your favorite Brazilian dish?",
    "Have you ever taken any unusual courses that few people know about?",
    "What is your favorite mobile app or game?",
    "Have you ever been part of an interesting group or club?",
    "What is your special culinary skill?",
    "What is your favorite TV or streaming station for series?",
    "What is your dream trip?",
    "If you could live anywhere in the world, where would it be?",
    "What is your most unusual talent?",
    "Have you ever tried any strange foods while traveling?",
    "What is your favorite team sport?",
    "If you could be a character from a book, who would it be?",
    "What is the most adventurous thing you have done?",
    "If you were a film director, what type of movie would you make?",
    "What is your favorite place to spend vacations?",
    "Have you ever done any volunteer work abroad?",
    "What is your favorite non-alcoholic drink?",
    "What is your favorite soundtrack for relaxation?",
    "If you could have a collection of something, what would it be?",
    "What is your favorite restaurant dish?",
    "Have you had any unusual experiences with food?",
    "What is your favorite outdoor activity?",
    "If you could write a book, what would it be about?",
    "What is your favorite Brazilian city to visit?",
    "Have you taken any interesting online courses?",
    "What is your favorite travel app?",
    "If you could have a conversation with a famous scientist, who would it be?",
    "What is your funniest school memory?",
    "What is your favorite holiday and how do you celebrate it?",
    "Have you ever been on an adventure trip?",
    "What is your favorite 90s TV series?",
    "If you were a video game character, who would you choose?",
    "What is the funniest thing that has happened at a party?",
    "What is your favorite street food?",
    "If you could have an exotic pet, what would it be?",
    "What is your favorite radio station or podcast?",
    "Have you ever volunteered for an animal-related cause?",
    "What is your favorite Olympic sport to watch?",
    "If you could be an action movie character, who would it be?",
    "What is your favorite family tradition?",
    "Have you had any funny experiences at an amusement park?",
    "What is your favorite regional Brazilian food?",
    "If you could have a house anywhere in the world, where would it be?",
    "What is your most ambitious personal project?",
    "What is your favorite type of music to listen to while working?",
    "Do you have a favorite inspirational quote?",
    "If you could meet any historical figure, who would it be?",
    "What is your favorite karaoke song?",
    "Have you been part of a sports team?",
    "What is the most interesting place you've visited for work?",
    "If you could have any pet, real or fictional, what would it be?",
    "What is the most memorable show you've watched?",
    "Are you a morning person or a night owl?",
    "What is the best advice you've ever received?",
    "Do you have any hidden talents?",
    "What is the last hobby you picked up?",
    "If you could live in any era of history, which would you choose?",
    "Have you ever tried creative writing?",
    "What is the most adventurous thing you've done recently?",
    "What is your favorite board game or card game?",
    "Do you collect anything interesting?",
    "Would you go to space if you could?",
    "What is your favorite way to relax after a long day of work?",
    "Do you have a favorite charity or cause you support?",
    "What is the most unusual food you've ever tried?",
    "If you could visit any fictional world from a book or movie, where would you go?",
    "What is the most valuable lesson you've learned from a mistake?",
    "Do you have a favorite historical event that fascinates you?",
    "If you could instantly learn a new skill, what would it be?",
    "What is your go-to comfort food when you're feeling down?",
    "What is the best book you've read recently?",
    "Have you ever taken a spontaneous trip somewhere?",
    "What is your favorite type of art or artistic style?",
    "Do you have a favorite outdoor activity?",
    "If you could attend any major sports event, which would it be?",
    "What is the most beautiful natural place you've visited?",
    "Do you have any interesting family traditions?",
    "What is the most thrilling adventure you've had in nature?",
    "If you could have dinner with any fictional character, who would it be?",
    "What is your favorite type of museum to visit?",
    "Have you tried your hand at photography?",
    "What is the most unusual job you've ever had?",
    "Do you have a favorite type of cuisine?",
    "What is the best way to spend a lazy Sunday for you?",
    "Have you ever participated in a talent show?",
    "If you could travel back in time, which era would you like to explore?",
    "What is your favorite holiday tradition?",
    "Do you enjoy stargazing or astronomy?",
    "What is your favorite dessert to indulge in?",
    "If you could have any exotic animal as a pet, what would it be?",
    "What is your favorite dance style?",
    "If you could have a superpower for a day, what would it be?",
    "What is the best advice you've ever given to someone?",
    "If you could witness any historical event, what would it be?",
    "What is the most delicious dish you've tried during a trip?",
    "Do you have any favorite TED Talks or motivational speakers?",
    "What is the most breathtaking view you've seen on a hike?",
    "If you could visit any fictional literary world, where would you go?",
    "What is your favorite way to give back to the community?",
    "Have you ever attempted to solve a challenging puzzle or riddle?",
    "What is the most fascinating encounter you've had with animals?",
    "If you could have a conversation with a famous inventor, who would it be?",
    "What is the most inspiring natural phenomenon you've witnessed?",
    "What is your favorite holiday and how do you celebrate it?",
    "Do you enjoy stargazing or astronomy?",
    "What is your favorite dessert to indulge in?",
    "If you could have any exotic animal as a pet, what would it be?",
    "What is your favorite classic novel?",
    "Have you been part of any club or organization outside of work?",
    "What is your preferred way to exercise?",
    "If you could be a video game character, who would you choose?",
    "What's the funniest thing that has happened to you recently?",
    "Do you have any favorite TED Talks or motivational speakers?",
    "If you could visit an ancient civilization, which one would it be?",
    "What is your favorite local restaurant, and what dish do you recommend?",
    "Have you ever tried a challenging outdoor activity like rock climbing or hiking?",
    "What is the most unusual pet you've ever had?",
    "Do you have a favorite dance style?",
    "If you could have a superpower for a day, what would it be?",
    "What is the best advice you would give to your younger self?",
    "Have you ever attended a cultural festival or celebration?",
    "What is the most interesting documentary you've watched recently?",
    "If you could instantly learn to play a musical instrument, which one would it be?",
    "What is your favorite spot in your hometown?",
    "Do you have a favorite motivational book?",
    "Have you ever attended a comic convention or fan expo?",
    "If you could have a private tour of any famous landmark, which one would it be?",
    "What is the most beautiful beach you've visited?",
    "Do you enjoy gardening or taking care of plants?",
    "What is your favorite architectural style?",
    "Have you ever tried cooking a new cuisine?",
    "If you could attend any major music festival, which one would it be?",
    "What is the most unique cultural tradition you've encountered during your travels?",
    "Do you have a favorite time of day?",
    "What is the most amazing wildlife encounter you've had?",
    "If you could have a conversation with a famous inventor, who would it be?",
    "What is the most inspiring natural phenomenon you've witnessed?",
    "Have you ever participated in a charity race or walk?",
    "What is the best advice you've ever given to someone?",
    "If you could witness any historical event, what would it be?",
    "What is the most delicious dish you've tried during a trip?",
    "Do you have any favorite podcast recommendations?",
    "What is the most breathtaking view you've seen during a hike?",
    "If you could visit any fantasy world from literature, where would you go?",
    "What is your favorite way to give back to the community?",
    "Have you ever tried to solve a challenging puzzle or riddle?",
    "What is the most fascinating encounter you've had with animals?",
    "If you could have a conversation with a famous scientist, who would it be?",
    "What is the most mesmerizing natural landmark you've visited?",
    "Do you have a favorite time period in history?",
    "What is the best advice you've received from a colleague?",
    "If you could have dinner with a famous artist, who would it be?",
    "What is the most charming cultural festival you've attended?",
    "Have you tried any DIY projects?",
    "What is the most inspiring travel destination you've visited?",
    "If you could meet an astronaut, who would it be?",
    "What is the most delicious dessert you've tried in a foreign country?",
    "Do you have a favorite science fiction book or movie?",
    "What is the most impressive natural park you've explored?",
    "If you could have a conversation with a famous philosopher, who would it be?",
    "Show a place you would like to visit one day.",
    "Post a picture of your favorite meal.",
    "Share a photo of your pet (if you have one).",
    "Show an image of something that makes you smile.",
    "Post a picture of your breakfast.",
    "Share a photo of a beautiful landscape you recently visited.",
    "Show a picture of your favorite book.",
    "Post a picture of your favorite hobby.",
    "Share a photo of something you cooked or baked.",
    "Show a picture of a movie you recently watched.",
    "Post a photo of a plant or flower you have at home.",
    "Share an image of something you're building or creating.",
    "Show a picture of a song you're currently listening to.",
    "Post a picture of a place you wish you were right now.",
    "Share a photo of an antique item you own.",
    "Show a picture of a typical Brazilian dish.",
    "Post a picture of a museum or exhibition you visited.",
    "Share a photo of an amazing sunset.",
    "Post a picture of an innovative product.",
    "Share an image of an object that represents your personality.",
    "Show a picture of a rainy day.",
    "Post a picture of an app you love.",
    "Share a photo of a famous landmark.",
    "Show a picture of a recipe you'd like to try.",
    "Post a picture of a board game you enjoy.",
    "Share a photo of an urban landscape at night.",
    "Show a picture of your dream car.",
    "What app do you use most on your phone?",
    "Have you ever witnessed your pet doing something strange?",
    "Which books do you think are worth reading?",
    "Share an unusual fact.",
    "Name three things you can't live without.",
    "What's something that costs less than $5.00 but brings instant happiness?",
    "Tell a moment when you instantly regretted an action.",
    "What's currently happening in your city?",
    "What's something you wouldn't want to try again?",
    "Would you rather be lucky or a genius?",
    "What's your favorite comfort food to brighten your day?",
    "Have you ever done something unexpected that surprised the people around you?",
    "What's the song that never leaves your head?",
    "What was the last movie you watched and loved?",
    "If you could time travel, which era would you like to go to?",
    "What do you do to relax after a long day at work?",
    "What is your favorite outdoor activity?",
    "What is the strangest item you own at home?",
    "If you could be a cartoon character, who would you choose?",
    "What's your secret hobby that few people know about?",
    "If you were a superhero, what would your superpower be?",
    "What's the most amazing place you've ever visited?",
    "What's the funniest thing that has happened to you in a meeting?",
    "What's your favorite Brazilian food dish?",
    "If you could switch places with someone for a day, who would you choose?",
    "What would you do if you won the lottery tomorrow?",
    "What's your favorite season, and why?",
    "If you could instantly learn a new skill, what would it be?",
    "Have you ever had a paranormal or unexplained experience?",
    "What's your current favorite TV show or series?",
    "What's your favorite joke?",
    "If you could have dinner with any living or deceased person, who would it be?",
    "What's your favorite social media app and why?",
    "If you had a free day with no obligations, how would you spend it?",
    "Have you ever participated in an extreme sport?",
    "What's your dream travel destination?",
    "If you had to choose only one food to eat for the rest of your life, what would it be?",
    "What's your funniest childhood memory?",
    "What's your hidden talent?",
    "If you could be an animal, what animal would you be and why?",
    "What's the funniest movie you've ever watched?",
    "What's the most exotic place you'd like to visit?",
    "If you could change professions for a day, what would you like to do?",
    "What is your favorite motivational quote?",
    "What would you do if you encountered an alien?",
    "What is your favorite board game?",
    "If you had a time machine, where and when would you go?",
    "What is your favorite book series?",
    "If you could have a meeting with a fictional character, who would you choose?",
    "What is your favorite type of music to relax to?",
    "Have you ever experienced an embarrassing situation at work?",
    "What's the best thing that has happened to you this year?",
    "What is your most cherished childhood memory?",
    "What would you do if you could be invisible for a day?",
    "If you had to live in a movie, which one would it be?",
    "What is your guilty pleasure?",
    "Who is your favorite superhero or villain?",
    "If you could solve a global problem, what would it be?",
    "What is your favorite productivity app?",
    "What is the best work-related tip you've ever received?",
    "If you could start your own company, what would its name be, and what industry would it be in?",
    "What is your favorite TV show from the 90s?",
    "What is your favorite homemade recipe?",
    "If you could have dinner with any historical figure, who would it be?",
    "What is your favorite movie quote?",
    "What is your favorite sport to watch?",
    "If you could travel to space, what would you like to see?",
    "What is your dream pet?",
    "If you had to choose only one app to use for the rest of your life, what would it be?",
    "What is your most effective productivity habit?",
    "What is the strangest thing you've ever eaten?",
    "What is your ideal workspace?",
    "What would you do if you won one million Brazilian reais?",
    "What is your most impressive culinary skill?",
    "If you could be a character from a book, who would you choose?",
    "What is your favorite TV cooking show?",
    "What is your favorite travel app?",
    "If you could instantly learn a language, which one would it be?",
    "What is your favorite sport to play?",
    "What is your favorite travel destination in Brazil?",
    "What is your idea of a perfect vacation?",
    "What is your funniest travel memory?",
    "If you could be famous for a day, how would you like to be remembered?",
    "What is your favorite museum?",
    "What is your favorite music app?",
    "If you could create a new tradition, what would it be?",
    "What is your favorite outdoor activity in Brazil?",
    "What is your favorite word or phrase in Portuguese?",
    "If you could have a meeting with a famous scientist, who would it be?",
    "What is your favorite place to relax?",
    "What is your preferred way to exercise?",
    "If you could have a conversation with a famous philosopher, what would you ask?",
    "What is your current personal project?",
    "If you could be a character from a horror movie, who would you choose?",
    "What is your favorite traditional Brazilian dish?",
    "If you could visit any city in the world, where would you go?",
    "What is your favorite Brazilian TV series?",
    "If you could change something in the world, what would it be?",
    "What is your favorite life motto?"
]